---
- name: Ejecutar comando 'free' en instancias de EC2 a través de AWS SSM
  hosts: aws_instances
  gather_facts: true
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_region: us-east-1  # Reemplaza con tu región
    ansible_aws_ssm_bucket_name: tu_bucket_ssm  # Reemplaza con el nombre de tu bucket SSM

  tasks:
    - name: Ejecutar el comando 'free' en el sistema
      command: free -m
      register: free_output
      ignore_errors: yes

    - name: Mostrar la salida de 'free'
      debug:
        var: free_output.stdout_lines
